CREATE TABLE IF NOT EXISTS eventcore_vendors (
    id INT AUTO_INCREMENT PRIMARY KEY,
    business_name VARCHAR(255),
    trading_name VARCHAR(255),
    registration_number VARCHAR(100),
    tin_vat VARCHAR(100),
    entity_type VARCHAR(50),
    registered_address TEXT,
    contact_person VARCHAR(255),
    contact_number VARCHAR(20),
    email VARCHAR(255),
    social_links TEXT,
    username VARCHAR(100),
    business_categories TEXT,
    business_description TEXT,
    logo_path VARCHAR(255),
    samples_path TEXT,
    plan_basic_annual TINYINT DEFAULT 0,
    plan_featured_weekly TINYINT DEFAULT 0,
    plan_featured_monthly TINYINT DEFAULT 0,
    plan_banner_weekly TINYINT DEFAULT 0,
    plan_banner_monthly TINYINT DEFAULT 0,
    vendor_name VARCHAR(255),
    signature_path VARCHAR(255),
    date DATE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);